apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kubernetes
images:
  - name: registry.invalid/drive9-csi
    newName: ghcr.io/drive9-ai/drive9-csi
    newTag: local
