apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.drive9.ai
spec:
  attachRequired: false
  podInfoOnMount: false
  requiresRepublish: false
  fsGroupPolicy: File
  volumeLifecycleModes:
    - Persistent
