apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret.example.yaml
  - csidriver.yaml
  - rbac.yaml
  - controller.yaml
  - node.yaml
  - storageclass.yaml
  - pvc.example.yaml
